FizzBuzzApplicationAviva/Models/FizzBuzzModel.cs
// <copyright file = "FizzBuzzModel.cs" company="TCS"> 
// TCS Bangalore. All rights reserved </copyright>
// <author>Manu Mohandas</author>

namespace FizzBuzzApplicationAviva.Models
{
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    /// <summary>
    /// Model class for the view.
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets or sets user input.
        /// </summary>
        [DisplayName("Enter Number")]
        [Required(ErrorMessage = "Please enter valid integer between 1 and 1000")]
        [Range(1, 1000, ErrorMessage = "Please enter valid integer between 1 and 1000")]
        public int? InputNumber { get; set; }

        /// <summary>
        /// Gets or sets the series.
        /// </summary>
        public PagedList<string> FizzBuzzSeries { get; set; }
    }
}

FizzBuzzApplicationAviva/Controllers/FizzBuzzController.cs
// <copyright file = "FizzBuzzController.cs" company="TCS"> 
// TCS Bangalore. All rights reserved </copyright>
// <author>Manu Mohandas</author>

namespace FizzBuzzApplicationAviva.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using FizzBuzzApplicationAviva.Models;
    using FizzBuzzService;
    using PagedList;

    /// <summary>
    /// The controller class.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// Service reference
        /// </summary>
        private readonly IFizzBuzzService fizzBuzzService;

        /// <summary>
        /// Records per page in the view
        /// </summary>
        private readonly int recordsPerPage;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class.
        /// </summary>
        /// <param name="fzBuzzService">The service class.</param>
        public FizzBuzzController(IFizzBuzzService fzBuzzService)
        {
            this.fizzBuzzService = fzBuzzService;
            this.recordsPerPage = 20;        
        }

        /// <summary>
        /// The Index method
        /// </summary>       
        /// <returns>The view result</returns>
        public ActionResult Index()
        {
            var model = new FizzBuzzModel();
            model.FizzBuzzSeries = new PagedList<string>(new List<string>(), 1, this.recordsPerPage);
            return this.View("FizzBuzzSeries", model);
        }

        /// <summary>
        /// The Action method
        /// </summary>
        /// <param name="model">The model for the view</param>
        /// <returns>The view result</returns>
        [HttpGet]
        public ActionResult GetSeries(FizzBuzzModel model, int? page)
        {
            var result = new List<string>();
            var maxNumber = (int)model.InputNumber;
            if (ModelState.IsValid)
            {
                result = this.fizzBuzzService.GetFizzBuzzSeries((int)model.InputNumber);
            }

            int pageNumber = page ?? 1;
            var pagedList = new PagedList<string>(result, pageNumber, this.recordsPerPage);
            model.FizzBuzzSeries = pagedList;
            return this.View("FizzBuzzSeries", model);
        }
    }
}

FizzBuzzApplicationAviva/Views/FizzBuzz/FizzBuzzSeries.cshtml
@model FizzBuzzApplicationAviva.Models.FizzBuzzModel
@using PagedList.Mvc
@{
    ViewBag.Title = "FizzBuzzSeries";
}

<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/FizzBuzz.css" rel="stylesheet" />

@Scripts.Render("~/bundles/jquery")
<body>
    @using (@Html.BeginForm("GetSeries", "FizzBuzz", FormMethod.Get))
    {
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    @Html.LabelFor(m => m.InputNumber)
                    @Html.TextBoxFor(m => m.InputNumber)
                    <input class="btn-info btn" type="submit" value="Submit" name="Submitbtn" id="Submitbtn" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-5" style="clear:both">
                    @Html.ValidationMessageFor(m => m.InputNumber)
                </div>
            </div>


            <div class="panel panel-body" style="float:left; clear:both">
                <h3>Series</h3>

                @foreach (var item in Model.FizzBuzzSeries)
                {
                    <div class="@item"> @item</div>
                }

                @Html.PagedListPager(Model.FizzBuzzSeries, page => Url.Action("GetSeries", new { page = page, InputNumber = Model.InputNumber }), PagedListRenderOptions.Minimal)               
            </div>
        </div>
    }
</body>

FizzBuzzApplicationAviva/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>